### ISSUE TITLE
user.getPhotoUrl().toString() null pointer exception

### ISSUE THREAD

**Issue by VihaanVerma89** [firebase/friendlypix#12]
I'm getting null pointer exception on loading image post. Uri returned from user.getPhotoUrl() is null

```
    public static Author getAuthor() {
        FirebaseUser user = FirebaseAuth.getInstance().getCurrentUser();
        if (user == null) return null;
        return new Author(user.getDisplayName(), user.getPhotoUrl().toString(), user.getUid());
    }
```

![screenshot from 2016-05-29 22 32 47](https://cloud.githubusercontent.com/assets/4493362/15634921/7b881578-25ed-11e6-9e8d-d9c1e7ee8c75.png)

Logcat

```
05-29 13:05:51.309 15438-15955/com.google.firebase.samples.apps.friendlypix E/AndroidRuntime: FATAL EXCEPTION: FirebaseStorage-Callbacks-1
                                                                                              Process: com.google.firebase.samples.apps.friendlypix, PID: 15438
                                                                                              java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
                                                                                                  at com.google.firebase.samples.apps.friendlypix.FirebaseUtil.getAuthor(FirebaseUtil.java:45)
                                                                                                  at com.google.firebase.samples.apps.friendlypix.NewPostUploadTaskFragment$UploadPostTask$2$2.onSuccess(NewPostUploadTaskFragment.java:182)
                                                                                                  at com.google.firebase.samples.apps.friendlypix.NewPostUploadTaskFragment$UploadPostTask$2$2.onSuccess(NewPostUploadTaskFragment.java:174)
                                                                                                  at com.google.firebase.storage.StorageTask$1.zza(Unknown Source)
                                                                                                  at com.google.firebase.storage.StorageTask$1.zzl(Unknown Source)
                                                                                                  at com.google.firebase.storage.zze$2.run(Unknown Source)
                                                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                                  at java.lang.Thread.run(Thread.java:818)
```

**Comment by tikurahul** [comment]
This is a bug in the sample code. `FirebaseUser#getPhotoUrl` is actually returns a `nullable` `Uri`.
Replace `user.getPhotoUrl().toString()` with `user.getPhotoUrl() != null ? user.getPhotoUrl().toString() : null`.

Better yet, you can submit a PR to fix the issue. 👍

**Comment by gkfillipus** [comment]
Hi i am also having the same problem with this code similar to above post 

FirebaseUser mUser = mFirebaseAuth.getCurrentUser();
        if (mUser != null) {
            // User is signed in
            Intent intent = new Intent(getApplicationContext(), MainActivity.class);
            String uid = mFirebaseAuth.getCurrentUser().getUid();
**`THIS` LINE**  String image = mFirebaseAuth.getCurrentUser().getPhotoUrl().toString();
            intent.putExtra("user_id", uid);
            if(image!=null){
                intent.putExtra("profile_picture",image);
            }
            startActivity(intent);
            startActivity(intent);
            finish();
            Log.d(TAG, "onAuthStateChanged:signed_in:" + mUser.getUid());
        }

any help

**Comment by jamespinto** [comment]
What is the solution for this?

the following suggestion by tikurahul dint work

Replace user.getPhotoUrl().toString() with user.getPhotoUrl() != null ? user.getPhotoUrl().toString() : null

**Comment by migueltarga** [comment]
```
if(mUser.getPhotoUrl() != null){
intent.putExtra("profile_picture",mUser.getPhotoUrl().toString());
}
```

**Comment by migueltarga** [comment]
```
public static Author getAuthor() {
        FirebaseUser user = FirebaseAuth.getInstance().getCurrentUser();
        if (user == null) return null;
        return new Author(user.getDisplayName(), user.getPhotoUrl() != null ? user.getPhotoUrl().toString() : null, user.getUid());
    }
```
@jamespinto  I agree with @tikurahul this should fix it, if the error in this line is:
` java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference`

**Comment by jamespinto** [comment]
nope! not working. I am using the google signin provider to log the user in.
According to the google documentation (the below code also gives me the same nullpointer exception)

Get a user's provider-specific profile information

To get the profile information retrieved from the sign-in providers linked to a user, use the getProviderData method. For example:

```
FirebaseUser user = FirebaseAuth.getInstance().getCurrentUser();
if (user != null) {
    for (UserInfo profile : user.getProviderData()) {
        // Id of the provider (ex: google.com)
        String providerId = profile.getProviderId();

        // UID specific to the provider
        String uid = profile.getUid();

        // Name, email address, and profile photo Url
        String name = profile.getDisplayName();
        String email = profile.getEmail();
        Uri photoUrl = profile.getPhotoUrl();
    };
}
```
https://firebase.google.com/docs/auth/android/manage-users#get_a_users_provider-specific_profile_information

**Comment by gkaldev** [comment]
This issue was moved to firebase/friendlypix-android#27
