### ISSUE TITLE
App crashes after login from google plus

### ISSUE THREAD

**Issue by VihaanVerma89** [firebase/friendlypix#2]
I have substituted my firebase storage bucket in "google_storage_bucket"  variable in strings.xml

but the app crashes  after google login.
Called from function 
**showSignedInUI**

crashes on this lin
```
        FirebaseUtil.getPeopleRef().child(firebaseUser.getUid()).updateChildren(
                updateValues,
                new DatabaseReference.CompletionListener() {
                    @Override
                    public void onComplete(DatabaseError firebaseError, DatabaseReference databaseReference) {
                        if (firebaseError != null) {
                            Toast.makeText(ProfileActivity.this,
                                    "Couldn't save user data: " + firebaseError.getMessage(),
                                    Toast.LENGTH_LONG).show();
                        }
                    }
                });
```

05-21 08:09:05.094 14758-18018/com.google.firebase.samples.apps.friendlypix I/FA: Tag Manager is not found and thus will not be used
05-21 08:09:05.290 14758-14758/com.google.firebase.samples.apps.friendlypix D/FirebaseCrashApiImpl: throwable com.google.firebase.database.DatabaseException: Failed to get FirebaseDatabase instance: FirebaseApp object has no DatabaseURL in its FirebaseOptions object.
05-21 08:09:05.336 14758-14758/com.google.firebase.samples.apps.friendlypix E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                              Process: com.google.firebase.samples.apps.friendlypix, PID: 14758
                                                                                              com.google.firebase.database.DatabaseException: Failed to get FirebaseDatabase instance: FirebaseApp object has no DatabaseURL in its FirebaseOptions object.
                                                                                                  at com.google.firebase.database.FirebaseDatabase.getInstance(Unknown Source)
                                                                                                  at com.google.firebase.database.FirebaseDatabase.getInstance(Unknown Source)
                                                                                                  at com.google.firebase.samples.apps.friendlypix.FirebaseUtil.getBaseRef(FirebaseUtil.java:27)
                                                                                                  at com.google.firebase.samples.apps.friendlypix.FirebaseUtil.getPeopleRef(FirebaseUtil.java:69)
                                                                                                  at com.google.firebase.samples.apps.friendlypix.ProfileActivity.showSignedInUI(ProfileActivity.java:199)
                                                                                                  at com.google.firebase.samples.apps.friendlypix.ProfileActivity.handleFirebaseAuthResult(ProfileActivity.java:176)
                                                                                                  at com.google.firebase.samples.apps.friendlypix.ProfileActivity.access$000(ProfileActivity.java:61)
                                                                                                  at com.google.firebase.samples.apps.friendlypix.ProfileActivity$2.onSuccess(ProfileActivity.java:159)
                                                                                                  at com.google.firebase.samples.apps.friendlypix.ProfileActivity$2.onSuccess(ProfileActivity.java:156)
                                                                                                  at com.google.android.gms.tasks.zze$1.run(Unknown Source)
                                                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                                  at android.os.Looper.loop(Looper.java:135)
                                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

How to fix this ?

**Comment by nicolasgarnier** [comment]
@gkaldevrel could you have a look?

**Comment by ianbarber** [comment]
D/FirebaseCrashApiImpl: throwable com.google.firebase.database.DatabaseException: Failed to get FirebaseDatabase instance: FirebaseApp object has no DatabaseURL in its FirebaseOptions object. 

looks to be the error. Can you check that the config file you're using has the database URL properly defined, and it didn't get tweaked in the strings when you were making the storage change?

**Comment by VihaanVerma89** [comment]
http://stackoverflow.com/questions/37363791/firebase-database-getinstance-crashes-app/37365886#37365886
