### ISSUE TITLE
App crash on Feed

### ISSUE THREAD

**Issue by MrThiago** [firebase/friendlypix#27]
After I login in and press Show feed the app crash:

07-22 10:52:04.942 14211-14211/com.google.firebase.samples.apps.friendlypixx E/UncaughtException: com.google.firebase.database.DatabaseException: Can't convert object of type java.lang.String to type com.google.firebase.samples.apps.friendlypixx.Models.Author
                                                                                                      at com.google.android.gms.internal.zzaix.zzd(Unknown Source)
                                                                                                      at com.google.android.gms.internal.zzaix.zzb(Unknown Source)
                                                                                                      at com.google.android.gms.internal.zzaix.zza(Unknown Source)
                                                                                                      at com.google.android.gms.internal.zzaix.zzb(Unknown Source)
                                                                                                      at com.google.android.gms.internal.zzaix$zza.zze(Unknown Source)
                                                                                                      at com.google.android.gms.internal.zzaix$zza.zzaC(Unknown Source)
                                                                                                      at com.google.android.gms.internal.zzaix.zzd(Unknown Source)
                                                                                                      at com.google.android.gms.internal.zzaix.zzb(Unknown Source)
                                                                                                      at com.google.android.gms.internal.zzaix.zza(Unknown Source)
                                                                                                      at com.google.firebase.database.DataSnapshot.getValue(Unknown Source)
                                                                                                      at com.firebase.ui.database.FirebaseRecyclerAdapter.parseSnapshot(FirebaseRecyclerAdapter.java:147)
                                                                                                      at com.firebase.ui.database.FirebaseRecyclerAdapter.getItem(FirebaseRecyclerAdapter.java:136)
                                                                                                      at com.firebase.ui.database.FirebaseRecyclerAdapter.onBindViewHolder(FirebaseRecyclerAdapter.java:176)
                                                                                                      at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5471)
                                                                                                      at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:5504)
                                                                                                      at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4741)
                                                                                                      at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4617)
                                                                                                      at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1994)
                                                                                                      at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1390)
                                                                                                      at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1353)
                                                                                                      at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:574)
                                                                                                      at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3028)
                                                                                                      at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2906)
                                                                                                      at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3283)
                                                                                                      at android.view.View.layout(View.java:15682)
                                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:580)
                                                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                                                      at android.view.View.layout(View.java:15682)
                                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                                                      at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1695)
                                                                                                      at android.view.View.layout(View.java:15682)
                                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                                                      at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:122)
                                                                                                      at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                                                                      at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1192)
                                                                                                      at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:814)
                                                                                                      at android.view.View.layout(View.java:15682)
                                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:580)
                                                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                                                      at android.view.View.layout(View.java:15682)
                                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                                                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                                                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                                                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                                                      at android.view.View.layout(View.java:15682)
                                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:580)
                                                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                                                      at android.view.View.layout(View.java:15682)
                                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                                                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                                                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                                                    at android.widget.LinearLayout.onLayout(LinearLa

**Comment by Divala** [comment]
Update your good play services in SDK Manager, then in gradle it should be 9.4.0

**Comment by gkaldev** [comment]
This issue was moved to firebase/friendlypix-android#23
