### ISSUE TITLE
PostsFragment$4.toggleLike(PostsFragment.java:188)

### ISSUE THREAD

**Issue by Inihood1** [firebase/friendlypix#96]
08-25 15:33:02.439 20002-20002/com.inihood.funspce.android E/UncaughtException: java.lang.NullPointerException: Attempt to invoke interface method 'void com.inihood.funspce.android.PostsFragment$OnPostSelectedListener.onPostLike(java.lang.String)' on a null object reference
at com.inihood.funspce.android.PostsFragment$4.toggleLike(PostsFragment.java:188)
at com.inihood.funspce.android.PostViewHolder$2.onClick(PostViewHolder.java:83)
at android.view.View.performClick(View.java:4802)
at android.view.View$PerformClick.run(View.java:20101)
at android.os.Handler.handleCallback(Handler.java:810)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:189)
at android.app.ActivityThread.main(ActivityThread.java:5529)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)

**Comment by gkaldev** [comment]
This issue was moved to firebase/friendlypix-android#4
